# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avator',
            field=models.ImageField(blank=True, null=True, upload_to='./avatar/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.BooleanField(default=0, verbose_name='性别'),
        ),
    ]
