# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='appreciation',
            field=models.TextField(blank=True, null=True, verbose_name='赏析'),
        ),
    ]
