# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0002_auto_20171105_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile',
            field=models.TextField(blank=True, null=True, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='author',
            name='quotation',
            field=models.TextField(blank=True, null=True, verbose_name='典故'),
        ),
    ]
