# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0003_auto_20171105_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='poems',
        ),
        migrations.AddField(
            model_name='poem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='poem.Category', verbose_name='分类'),
        ),
        migrations.AlterUniqueTogether(
            name='poem',
            unique_together=set([('title', 'author_name')]),
        ),
    ]
