# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0005_auto_20171109_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
